/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlinesurveysystem;

import javax.swing.*;
import java.sql.*;
/**
 *
 * @author Mintu's PC
 */
public class Survey extends javax.swing.JFrame {

    /**
     * Creates new form Survey
     */
    public Survey() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jOptionPane1 = new javax.swing.JOptionPane();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rb5 = new javax.swing.JRadioButton();
        rb6 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        rb9 = new javax.swing.JRadioButton();
        rb8 = new javax.swing.JRadioButton();
        rb7 = new javax.swing.JRadioButton();
        rb10 = new javax.swing.JRadioButton();
        rb12 = new javax.swing.JRadioButton();
        rb11 = new javax.swing.JRadioButton();
        rb14 = new javax.swing.JRadioButton();
        rb15 = new javax.swing.JRadioButton();
        rb13 = new javax.swing.JRadioButton();
        rb17 = new javax.swing.JRadioButton();
        rb18 = new javax.swing.JRadioButton();
        rb16 = new javax.swing.JRadioButton();
        rb19 = new javax.swing.JRadioButton();
        rb21 = new javax.swing.JRadioButton();
        rb20 = new javax.swing.JRadioButton();
        rb22 = new javax.swing.JRadioButton();
        rb23 = new javax.swing.JRadioButton();
        rb24 = new javax.swing.JRadioButton();
        rb26 = new javax.swing.JRadioButton();
        rb27 = new javax.swing.JRadioButton();
        rb25 = new javax.swing.JRadioButton();
        rb30 = new javax.swing.JRadioButton();
        rb28 = new javax.swing.JRadioButton();
        rb29 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        measuresField = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        ageField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(204, 204, 255));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Smartphone Addiction");

        jLabel2.setFont(new java.awt.Font("NSimSun", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 255));
        jLabel2.setText("Survey Form");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Age");

        jLabel5.setText("Q1. I can hardly concentrate at work when I am without my smartphone. ");

        jLabel6.setText("Q2. I feel sick when I am without my smartphone.");

        jLabel7.setText("Q3. I can't stop checking my smartphones when at work, in Public or with others.");

        jLabel8.setText("Q4. I spend more time with my smartphone than my family.");

        jLabel9.setText("Q5. I use my smartphone while driving/taking a walk.");

        jLabel10.setText("Q6.  I interrupt my sleep to use or read smartphone messages.");

        jLabel11.setText("Q7. I use my smartphone while using the convenience.");

        jLabel12.setText("Q8. I rather use my smartphone than engage in physical exercise.");

        jLabel13.setText("Q9. I my phone while reading/eating.");

        jLabel14.setText("Q10. I am irritable, restless or angry when unable to use my smartphone. ");

        jLabel15.setText("Did you take any measure to reduce your phone usage? If yes, mention it, if not write N/A.");

        rb1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rb1);
        rb1.setToolTipText("");
        rb1.setActionCommand("Rarely");
        rb1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        rb1.setBorderPainted(true);
        rb1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        rb2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rb2);
        rb2.setActionCommand("Sometimes");
        rb2.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));
        rb2.setBorderPainted(true);
        rb2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        rb3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rb3);
        rb3.setActionCommand("Always");
        rb3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        rb3.setBorderPainted(true);
        rb3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rb3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel16.setFont(new java.awt.Font("Vonique 43", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 255));
        jLabel16.setText("777 rees  Org .");

        jLabel17.setForeground(new java.awt.Color(102, 102, 255));
        jLabel17.setText("--------------------------------------------------------------------------------------------------------------------------------");

        jLabel18.setText("Rarely    Sometimes    Always");

        rb5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rb5);
        rb5.setActionCommand("Sometimes");
        rb5.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));
        rb5.setBorderPainted(true);
        rb5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        rb6.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rb6);
        rb6.setActionCommand("Always");
        rb6.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        rb6.setBorderPainted(true);
        rb6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rb6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        rb4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rb4);
        rb4.setActionCommand("Rarely");
        rb4.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        rb4.setBorderPainted(true);
        rb4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup3.add(rb9);
        rb9.setActionCommand("Always");
        rb9.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        rb9.setBorderPainted(true);
        rb9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rb9.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        rb8.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rb8);
        rb8.setActionCommand("Sometimes");
        rb8.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));
        rb8.setBorderPainted(true);
        rb8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        rb7.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup3.add(rb7);
        rb7.setActionCommand("Rarely");
        rb7.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        rb7.setBorderPainted(true);
        rb7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        rb10.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(rb10);
        rb10.setActionCommand("Rarely");
        rb10.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        rb10.setBorderPainted(true);
        rb10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup4.add(rb12);
        rb12.setActionCommand("Always");
        rb12.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        rb12.setBorderPainted(true);
        rb12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rb12.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        rb11.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup4.add(rb11);
        rb11.setActionCommand("Sometimes");
        rb11.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));
        rb11.setBorderPainted(true);
        rb11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        rb14.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(rb14);
        rb14.setActionCommand("Sometimes");
        rb14.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));
        rb14.setBorderPainted(true);
        rb14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup5.add(rb15);
        rb15.setActionCommand("Always");
        rb15.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        rb15.setBorderPainted(true);
        rb15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rb15.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        rb13.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup5.add(rb13);
        rb13.setActionCommand("Rarely");
        rb13.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        rb13.setBorderPainted(true);
        rb13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        rb17.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(rb17);
        rb17.setActionCommand("Sometimes");
        rb17.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));
        rb17.setBorderPainted(true);
        rb17.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup6.add(rb18);
        rb18.setActionCommand("Always");
        rb18.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        rb18.setBorderPainted(true);
        rb18.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rb18.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        rb16.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup6.add(rb16);
        rb16.setActionCommand("Rarely");
        rb16.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        rb16.setBorderPainted(true);
        rb16.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        rb19.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup7.add(rb19);
        rb19.setActionCommand("Rarely");
        rb19.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        rb19.setBorderPainted(true);
        rb19.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup7.add(rb21);
        rb21.setActionCommand("Always");
        rb21.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        rb21.setBorderPainted(true);
        rb21.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rb21.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        rb20.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup7.add(rb20);
        rb20.setActionCommand("Sometimes");
        rb20.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));
        rb20.setBorderPainted(true);
        rb20.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        rb22.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup8.add(rb22);
        rb22.setActionCommand("Rarely");
        rb22.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        rb22.setBorderPainted(true);
        rb22.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        rb23.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup8.add(rb23);
        rb23.setActionCommand("Sometimes");
        rb23.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));
        rb23.setBorderPainted(true);
        rb23.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup8.add(rb24);
        rb24.setActionCommand("Always");
        rb24.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        rb24.setBorderPainted(true);
        rb24.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rb24.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        rb26.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup9.add(rb26);
        rb26.setActionCommand("Sometimes");
        rb26.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));
        rb26.setBorderPainted(true);
        rb26.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup9.add(rb27);
        rb27.setActionCommand("Always");
        rb27.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        rb27.setBorderPainted(true);
        rb27.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rb27.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        rb25.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup9.add(rb25);
        rb25.setActionCommand("Rarely");
        rb25.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        rb25.setBorderPainted(true);
        rb25.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup10.add(rb30);
        rb30.setActionCommand("Always");
        rb30.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.red));
        rb30.setBorderPainted(true);
        rb30.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        rb30.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        rb28.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup10.add(rb28);
        rb28.setActionCommand("Rarely");
        rb28.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.green));
        rb28.setBorderPainted(true);
        rb28.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        rb29.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup10.add(rb29);
        rb29.setActionCommand("Sometimes");
        rb29.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.yellow));
        rb29.setBorderPainted(true);
        rb29.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        measuresField.setBackground(new java.awt.Color(204, 204, 255));
        measuresField.setColumns(20);
        measuresField.setRows(5);
        jScrollPane1.setViewportView(measuresField);

        submit.setBackground(java.awt.Color.red);
        submit.setFont(new java.awt.Font("Love Nature", 0, 18)); // NOI18N
        submit.setForeground(new java.awt.Color(239, 239, 239));
        submit.setText("SUBMIT");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        nameField.setBackground(new java.awt.Color(204, 204, 255));
        nameField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        nameField.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));

        ageField.setBackground(new java.awt.Color(204, 204, 255));
        ageField.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ageField.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb1)
                                        .addGap(38, 38, 38)
                                        .addComponent(rb2)
                                        .addGap(39, 39, 39)
                                        .addComponent(rb3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb4)
                                        .addGap(38, 38, 38)
                                        .addComponent(rb5)
                                        .addGap(39, 39, 39)
                                        .addComponent(rb6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb7)
                                        .addGap(38, 38, 38)
                                        .addComponent(rb8)
                                        .addGap(39, 39, 39)
                                        .addComponent(rb9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb10)
                                        .addGap(38, 38, 38)
                                        .addComponent(rb11)
                                        .addGap(39, 39, 39)
                                        .addComponent(rb12))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb13)
                                        .addGap(38, 38, 38)
                                        .addComponent(rb14)
                                        .addGap(39, 39, 39)
                                        .addComponent(rb15))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb16)
                                        .addGap(38, 38, 38)
                                        .addComponent(rb17)
                                        .addGap(39, 39, 39)
                                        .addComponent(rb18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb19)
                                        .addGap(38, 38, 38)
                                        .addComponent(rb20)
                                        .addGap(39, 39, 39)
                                        .addComponent(rb21))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb22)
                                        .addGap(38, 38, 38)
                                        .addComponent(rb23)
                                        .addGap(39, 39, 39)
                                        .addComponent(rb24))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb25)
                                        .addGap(38, 38, 38)
                                        .addComponent(rb26)
                                        .addGap(39, 39, 39)
                                        .addComponent(rb27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rb28)
                                        .addGap(38, 38, 38)
                                        .addComponent(rb29)
                                        .addGap(39, 39, 39)
                                        .addComponent(rb30))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(submit)
                                        .addGap(56, 56, 56)))
                                .addGap(16, 16, 16))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel18)
                    .addComponent(ageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rb3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rb1))
                    .addComponent(rb2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rb6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rb4))
                    .addComponent(rb5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rb9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rb7))
                    .addComponent(rb8))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rb10))
                            .addComponent(rb11))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rb13))
                            .addComponent(rb14))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rb18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rb16))
                    .addComponent(rb17))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rb21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rb19))
                    .addComponent(rb20))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rb24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rb22))
                    .addComponent(rb23))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rb27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rb25))
                    .addComponent(rb26))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rb30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rb28))
                            .addComponent(rb29))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(submit)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        if(nameField.getText().equals("") || ageField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please enter your Name and Age before submitting!");
           return;
        }
        if (buttonGroup1.getSelection() == null || buttonGroup2.getSelection() == null || buttonGroup3.getSelection() == null || buttonGroup4.getSelection() == null || buttonGroup5.getSelection() == null || buttonGroup6.getSelection() == null || buttonGroup7.getSelection() == null || buttonGroup8.getSelection() == null || buttonGroup9.getSelection() == null || buttonGroup10.getSelection() == null || measuresField.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Please answer all the questions.");
            return;
        }        
        
        String uname = nameField.getText();
        String uage = ageField.getText();
        String q1a = buttonGroup1.getSelection().getActionCommand();
        String q2a = buttonGroup2.getSelection().getActionCommand();
        String q3a = buttonGroup3.getSelection().getActionCommand();
        String q4a = buttonGroup4.getSelection().getActionCommand();
        String q5a = buttonGroup5.getSelection().getActionCommand();
        String q6a = buttonGroup6.getSelection().getActionCommand();
        String q7a = buttonGroup7.getSelection().getActionCommand();
        String q8a = buttonGroup8.getSelection().getActionCommand();
        String q9a = buttonGroup9.getSelection().getActionCommand();
        String q10a = buttonGroup10.getSelection().getActionCommand();
        String umeasures = measuresField.getText();      
        
        String query = "insert into smartphone_addiction_survey_data values ('"+uname+"' , '"+uage+"'  , '"+q1a+"'  , '"+q2a+"'  , '"+q3a+"'  , '"+q4a+"'  , '"+q5a+"'  , '"+q6a+"'  , '"+q7a+"'  , '"+q8a+"'  , '"+q9a+"'  , '"+q10a+"'  , '"+umeasures+"' )";

                   
            try {                
                Conn c = new Conn();
                c.s.executeUpdate(query);
                
                JOptionPane.showMessageDialog(null, "Thank you for participating in our survey.");
                
                
                
                
            } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        

    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Survey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Survey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea measuresField;
    private javax.swing.JTextField nameField;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb11;
    private javax.swing.JRadioButton rb12;
    private javax.swing.JRadioButton rb13;
    private javax.swing.JRadioButton rb14;
    private javax.swing.JRadioButton rb15;
    private javax.swing.JRadioButton rb16;
    private javax.swing.JRadioButton rb17;
    private javax.swing.JRadioButton rb18;
    private javax.swing.JRadioButton rb19;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb20;
    private javax.swing.JRadioButton rb21;
    private javax.swing.JRadioButton rb22;
    private javax.swing.JRadioButton rb23;
    private javax.swing.JRadioButton rb24;
    private javax.swing.JRadioButton rb25;
    private javax.swing.JRadioButton rb26;
    private javax.swing.JRadioButton rb27;
    private javax.swing.JRadioButton rb28;
    private javax.swing.JRadioButton rb29;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb30;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rb5;
    private javax.swing.JRadioButton rb6;
    private javax.swing.JRadioButton rb7;
    private javax.swing.JRadioButton rb8;
    private javax.swing.JRadioButton rb9;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
